### ISSUE TITLE
Map: Support clipboard operations for features

### ISSUE THREAD

**Issue by csingewald** [syncpoint/ODIN#135]
Support clipboard operations like copy, paste, cut, ...

**Comment by dehmer** [comment]
Support the following operation
* Copy: copy selected features into clipboard
* Cut: copy selected features into clipboard, delete features from map
* Paste: insert features from clipboard into map
* Delete: delete selected features from map

Later it should also be possible to 
* copy features from one project to another project
* copy selected feature as graphics to another (office) application

Currently we have no answers to the following questions
* Into which layer should features be pasted (active layer)?
* (How) should a (pixel) offset be calculated on paste?
* What exactly is "the clipboard"? Will Electron clipboard do or do we need something extra?

Reference
* https://www.electronjs.org/docs/api/clipboard

**Comment by dehmer** [comment]
From what I understand from the Electron API documentation, clipboard is not sufficient for what we need. I.e. to store serialized (JSON/object) form of features including geometry and properties.

Electron's (system) clipboard (only) supports formats used to exchange data with other application:
* text String (optional)
* html String (optional)
* image NativeImage (optional)
* rtf String (optional)
* bookmark String (optional) - The title of the URL at text.

Application-specific MIME types are not supported.

So I guess we will need an internal clipboard which is reserved for/restricted to map features. It would probably be best to maintain an appropriate data structure in main process in order to pass clipboard contents between renderers. System clipboard can later be used to additionally hold standard formats to be exchanged with other applications (especially image data).

**Comment by ThomasHalwax** [comment]
@dehmer With the latest PR #323 alle common clipboard actions are implemented. Do you think we can close this one?

**Comment by dehmer** [comment]
Yes, please.
