### ISSUE TITLE
Equipment - Symbols are missing or wrong displayed on the map

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#171]
The following symbols for equipment are missing or wrong displayed on the map:

SIDC 2525c (following example all with the Modifier (F) for friend on the Postion 2) / Hierachy Code:

SFAPWMSU--***** | WAR.AIRTRK.WPN.MSLIF.SLM.SSUM
SFAPWMAP--***** | WAR.AIRTRK.WPN.MSLIF.ALM.ASPC
SFAPWMU---***** | WAR.AIRTRK.WPN.MSLIF.SBSM
**text in symbol is in the wrong position**

SFAPWMCM--***** | WAR.AIRTRK.WPN.MSLIF.CM
**no symbol could be created on the map**

SFGPE-----***** | WAR.GRDTRK.EQT
**no symbol available for selcetion, because the symbol for the ground track has been assigned to the special equipment 1.X.3.2.4 WAR.GRDTRK.EQT.SPL (in 2525c this is indicated by "N/A")**

SFAP------***** | WAR.AIRTRK
**no symbol available for selcetion, because the symbol for the air track has been assigned to the air track signal intercept 4.X.2 SIGINT.AIRTRK (in 2525c this is indicated by "N/A")**

SFSP------***** | WAR.SSUF
**no symbol available for selcetion (the similiar sea surface track own track 1.X.4.4 WAR.SSUF.OWN is available and correctly displayed in ODIN)**

EFOPEA----***** | EMS.OPN.SNS.BIO
EFOPEB----***** | EMS.OPN.SNS.CML
EFOPEC----***** | EMS.OPN.SNS.INT
EFOPED----***** | EMS.OPN.SNS.NUC
EFOPEE----***** | EMS.OPN.SNS.RAD
**no symbol available for selection and therefore can't be created on the map**

**Comment by harrywipperfuerth** [comment]
### **_Update 23jun20_**

(the entry of 25feb20 must therefore be regarded as oboslet):

Due to the change from version 0.5.4 to version 0.6.0/OL and the resulting reimplementation of the symbols 2525C, the following incorrect representations in the equipment range were found during the check:

The following symbols for equipment are wrong displayed on the map:

SIDC 2525c (following example all with the Modifier (F) for friend on the Position 2) / Hierachy Code:

SFAPWMSU--***** / WAR.AIRTRK.WPN.MSLIF.SLM.SSUM
SFAPWMAP--***** / WAR.AIRTRK.WPN.MSLIF.ALM.ASPC
SFAPWMU---***** /  WAR.AIRTRK.WPN.MSLIF.SBSM
**text in symbol is in the wrong position**

EFOPEE----***** / EMS.OPN.SNS.RAD
**text "RAD" is wrong, only "R" is displayed in the symbol according 2525C**

SFAPWMCM--***** / WAR.AIRTRK.WPN.MSLIF.CM
**no symbol could be created on the map, but properties set is available**

SFGPES----***** / EMS.OPN.SNS
**the same symbol is in ground track equipment  available, but yout don't find it as EMS equipment**

For **_54 "civilian" symbols_** (Vehicles, Air, Maritime) the display on the map is **_according to 2525D_** (colour of the sybombole is "purple", only for enemy status the display is "red").

My suggestion is to **_make no changes_** here and to leave the current "state" as it is the intention to change to 2525D.

**Comment by dehmer** [comment]
<img width="319" alt="Screenshot 2020-11-16 at 08 13 06" src="https://user-images.githubusercontent.com/322462/99222820-a2f5a880-27e3-11eb-8820-986f6cb24afe.png">

 1. SFAPWMSU--*****: slightly wrong icon (upstream)
 2. SFAPWMAP--*****: slightly wrong icon (upstream)
 3. SFAPWMU---*****: slightly wrong icon (upstream)
 4. SFAPWMCM--*****: fixed wrong SIDC in MIP/MIG
 5. SFGPE-----*****: fixed since 0.6.0 (search: +scope:equipment +dimension:land)
 6. SFAP------*****: fixed since 0.6.0 (search: +scope:equipment +dimension:space)
 7. SFSP------*****: fixed since 0.6.0 (search: +scope:equipment +dimension:surface)
 8. EFOPEA----*****: fixed since 0.6.0
 9. EFOPEB----*****: fixed since 0.6.0
10. EFOPEC----*****: fixed since 0.6.0
11. EFOPED----*****: fixed since 0.6.0
12. EFOPEE----*****: slightly wrong icon (upstream)

**Comment by dehmer** [comment]
No further actions required.
Closing.
