### ISSUE TITLE
support military symbols defined by MIL-STD-2525D 

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#228]
ODIN should use military symbols defined by [MIL-STD-2525D](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwjkwqiP17LoAhUNsaQKHey8DK8QFjAAegQIARAB&url=https%3A%2F%2Fwww.jcs.mil%2FPortals%2F36%2FDocuments%2FDoctrine%2FOther_Pubs%2Fms_2525d.pdf&usg=AOvVaw3RMdvardJv6yMt81S5hQ2s)

Consider [ESRI's GitHub repository](https://github.com/Esri/joint-military-symbology-xml) for this issue.

**Comment by dehmer** [comment]
Does this mean, we would drop support for 2525-C.
We have tons of data, which must be "upgraded" in that case.

**Comment by harrywipperfuerth** [comment]
We should take the step towards 2525d, because from version 2525d on, it is identical with App6D and complies with the current military standard.

The question one can ask is whether one is willing to support both 2525c and 2525d in the program.

**Comment by dehmer** [comment]
I highly recommend to postpone MIL-STD-2525D until we completed Charlie.
Please comment and ideally close for now.

**Comment by harrywipperfuerth** [comment]
I agree with you that we should first complete MIL-STD 2525C so that users can use it in ODIN without restrictions.

Nevertheless I would not close the issue.

If it's about focusing the issue list on the next following/needed steps for immediate implementation, I would create a second section (e.g. Epic, Future etc.) in GitHub to collect all future (as yet unspecified) suggestions/ideas etc.

If such issues are closed, there is a danger that they will not be considered anymore.

Translated with www.DeepL.com/Translator (free version)

**Comment by dehmer** [comment]
@harrywipperfuerth Sorry, no it's not.
If the need to support 2525D becomes stronger, we will support it and re-open this issue.
Closing for now.
