### ISSUE TITLE
Map: Leaflet attribution control links are active

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#29]
Clicking on a link in attribution control opens a new page, without a way to navigate back.
In an offline environment this poses an additional problem.

**Comment by JulianKK** [comment]
My first thought was to open the answers of a link in the default browser by adding this piece of code:

`window.webContents.on('will-navigate', (event, url) => {
      event.preventDefault()
      shell.openExternal(url)
    })`

but the hot-module replacement mode stops working when I do that.

Vladimir Agafonkin himself said: "... you are absolutely free to remove it. It is there by default to help with Leaflet adoption (because many devs don't care if it's present), but it's not required by any means." 

So I think we will hide it for the moment

**Comment by dehmer** [comment]
Do it. Less is more.
Thanks!
