### ISSUE TITLE
Exception when dropping a GeoJSON file on the map

### ISSUE THREAD

**Issue by ThomasHalwax** [syncpoint/ODIN#342]
I created a GeoJSON file that contains the federal borders of Tirol with QGIS. When I drag and drop the file on the map ODIN throws an exception:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/38359572/97861473-21dae380-1d04-11eb-814d-a97e0ea0db6a.png">

[06_TIROL_Grenzen_Land.json.zip](https://github.com/syncpoint/ODIN/files/5474492/06_TIROL_Grenzen_Land.json.zip)

After reloading ODIN renders the data correctly:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/38359572/97861768-8eee7900-1d04-11eb-953e-eebfbf963946.png">

**Comment by dehmer** [comment]
The feature in the file does not have a SIDC, but lookup in feature descriptors requires one to infer properties panel, geometry layout, etc.
In the future we should provide a generic properties panel (or geometry-based properties panels.)
In the meantime this was fixed by not showing a properties panel when no SIDC was given.
