### ISSUE TITLE
Object "Strong Point" is missing

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#395]
In Odin, the object "Strong Point" is currently displayed only as a "normal" area on the map.

The object should be displayed in the correct shape:

![2525C - Strong Point](https://user-images.githubusercontent.com/49548300/107934635-9a4a7500-6f80-11eb-8d66-bad2828dae42.PNG)

Example on the map:

![grafik](https://user-images.githubusercontent.com/49548300/107935388-9e2ac700-6f81-11eb-9cc7-94e2383df62d.png)

**Comment by dehmer** [comment]
I think the given example is a little misleading, because the shape should probably not be changed by line smoothing or similar. If an area consists of four points, for example, no additional points should be inserted automatically. Given the below example, the "spikes" in the first area are to drawn exactly at the four area sides. The second area would more closely match the above example.

<img width="562" alt="Screenshot 2021-02-24 at 10 41 42" src="https://user-images.githubusercontent.com/322462/108981817-66143a00-768d-11eb-805a-85b9eb3440c1.png">

**Comment by dehmer** [comment]
First attempt: Not too shabby.

<img width="640" alt="Screenshot 2021-02-26 at 08 21 04" src="https://user-images.githubusercontent.com/322462/109269000-2aec4500-780c-11eb-9e6b-ad5ee11b5d9b.png">
