### ISSUE TITLE
No map visibile during zooming in to "deep"

### ISSUE THREAD

**Issue by harrywipperfuerth** [syncpoint/ODIN#43]
If you zoom in too far on the different maps, no more map will be displayed.

The system should only zoom in so that the map is still visible at the maximum zoom level.

**Comment by dehmer** [comment]
Min and max zoom levels of map are already limited to the values defined by the tile provider.
It is not possible to zoom to a level which is not supported by the respective tile provider.

In cases where no tiles are loaded and displayed, the tile provider most probably rejected the request, or connectivity is otherwise limited or broken. 

If we detect such a situation however, we should indicate to the user, that connectivity is limited for whatever reason.

**Comment by dehmer** [comment]
Closing, nothing to fix; see #44.
