### ISSUE TITLE
Go to coordinate

### ISSUE THREAD

**Issue by dehmer** [syncpoint/ODIN#9]
The user should be able to pan the map to a specific coordinate.

Supported coordinate formats:
* Latitude/longitude (WGS84): different formats
* UTM/UTMREF
* MGRS

**Discussion**: What are use cases for this feature?
**Discussion**: Should we mark the coordinate on the map, how and for how long?

**Comment by harrywipperfuerth** [comment]
Use case:
You will receive a situation report (radio, document, mail ...) with the detail coordinates of an unit and want to find quickly the location of the unit on the map.

The coordinate must be marked in any case, so that the user knows the exact location on the map in order to be able to place the corresponding unit there.

The marking should remain until the user removes it manually = "work is done".

**Comment by dehmer** [comment]
@harrywipperfuerth So the general use case is 'report entry' (own/enemy unit/equipment). 

Why not directly placing some sort of placeholder (blue/red/unknown dot) and then successively specifying necessary type and other information from the report for this placeholder (in case no ORBAT/task organisation is available)?

Do you see the necessity for 'go to coordinate/location' in the broader context of mission planning?
If not, I'd propose to defer this issue until we go for COP/report functionality.

**Comment by dehmer** [comment]
Currently, we can copy coordinates to clipboard, then reverse place search with this coordinates will find the closed feature from OSM. Picking this place, map pans center to this place.

<img width="337" alt="Screen Shot 2019-08-31 at 11 43 33" src="https://user-images.githubusercontent.com/322462/64062275-c0415580-cbe4-11e9-94d4-46a79abaaa75.png">
